extends "res://tests/framework/test_case.gd"
## DataRegistry: loading, the DATA_CONTRACT shapes, and the JSON-float fix.

var _saved_level: int = 0


func before_each() -> void:
	_saved_level = Log.level
	Log.level = Log.Level.ERROR
	# Deterministic content: fixtures are committed and contract-shaped.
	DataRegistry.boot(DataRegistry.FIXTURE_DIR)


func after_each() -> void:
	Log.level = _saved_level


# --------------------------------------------------------------------------

func test_boot_loads_every_contract_table() -> void:
	is_true(DataRegistry.is_loaded(), "registry reports loaded")
	check(DataRegistry.species_count() > 0, "species loaded")
	check(DataRegistry.move_count() > 0, "moves loaded")
	check(DataRegistry.learnset_count() > 0, "learnsets loaded")
	check(DataRegistry.ability_count() > 0, "abilities loaded")
	eq(DataRegistry.type_names().size(), 18, "18 types incl. fairy")
	eq(DataRegistry.level_cap_count(), 15, "15 level cap rows")


func test_species_table_is_the_full_national_dex() -> void:
	# data/species.json is generated by the data stream. When it exists it must
	# be the whole dex; until then, prove the loader on the fixture and say so.
	DataRegistry.boot(DataRegistry.DATA_DIR)
	if DataRegistry.source_of("species") == "data":
		eq(DataRegistry.species_count(), DataRegistry.EXPECTED_SPECIES,
			"data/species.json national dex size")
		is_true(DataRegistry.has_species(1), "Bulbasaur present")
		is_true(DataRegistry.has_species(1025), "Pecharunt present")
	else:
		pending("data/species.json absent (source=%s) -- the 1025-species assertion "
			% DataRegistry.source_of("species")
			+ "cannot run yet; loaded %d fixture species instead" % DataRegistry.species_count())
		check(DataRegistry.species_count() > 0, "fixture species still load")


func test_species_record_matches_the_contract() -> void:
	# Pikachu is the worked example in docs/DATA_CONTRACT.md section 1.
	var p := DataRegistry.get_species(25)
	eq(int(p.get("id", 0)), 25, "id")
	eq(String(p.get("name", "")), "Pikachu", "name")
	eq(Array(p.get("types", [])), ["electric"], "types")
	var stats: Dictionary = p.get("stats", {})
	eq(int(stats.get("hp", 0)), 35, "hp")
	eq(int(stats.get("atk", 0)), 55, "atk")
	eq(int(stats.get("def", 0)), 40, "def")
	eq(int(stats.get("spa", 0)), 50, "spa")
	eq(int(stats.get("spd", 0)), 50, "spd")
	eq(int(stats.get("spe", 0)), 90, "spe")
	eq(Array(p.get("abilities", [])), ["static"], "abilities")
	eq(String(p.get("hiddenAbility", "")), "lightning-rod", "hiddenAbility")
	eq(String(p.get("growthRate", "")), "medium-fast", "growthRate")
	eq(int(p.get("baseExp", 0)), 112, "baseExp")
	eq(int(p.get("catchRate", 0)), 190, "catchRate")
	eq(int(p.get("genderRate", -99)), 4, "genderRate")
	eq(Array(p.get("eggGroups", [])), ["field", "fairy"], "eggGroups")
	eq(int(p.get("hatchCounter", 0)), 10, "hatchCounter")
	eq(int(p.get("height", 0)), 4, "height in decimetres")
	eq(int(p.get("weight", 0)), 60, "weight in hectograms")
	eq(int(p.get("evolvesFrom", 0)), 172, "evolvesFrom Pichu")
	var evo: Dictionary = (p.get("evolutions", []) as Array)[0]
	eq(int(evo["to"]), 26, "evolves to Raichu")
	eq(String(evo["method"]), "use-item", "evolution method")
	eq(String(evo["item"]), "thunder-stone", "evolution item")


func test_numbers_are_ints_not_json_floats() -> void:
	# JSON.parse_string returns TYPE_FLOAT for every number on this engine.
	# _intify() is the single boundary that undoes it; if it regresses, every
	# dex id used as a Dictionary key silently stops matching.
	var p := DataRegistry.get_species(25)
	is_int(p["id"], "species id")
	is_int((p["stats"] as Dictionary)["hp"], "base hp")
	is_int(p["baseExp"], "baseExp")
	is_int(p["generation"], "generation")
	var m := DataRegistry.get_move_by_name("thunderbolt")
	is_int(m["id"], "move id")
	is_int(m["power"], "move power")
	var pair: Array = (DataRegistry.get_learnset(25)["levelUp"] as Array)[0]
	is_int(pair[0], "learnset level")
	is_int(DataRegistry.get_level_cap(2), "level cap")


func test_unknown_ids_degrade_instead_of_crashing() -> void:
	eq(DataRegistry.get_species(99999), {}, "unknown species -> empty dict")
	is_false(DataRegistry.has_species(99999), "has_species false")
	eq(DataRegistry.get_move(99999), {}, "unknown move -> empty dict")
	eq(DataRegistry.get_ability(99999), {}, "unknown ability -> empty dict")
	eq(DataRegistry.get_base_stat(99999, "hp"), 0, "unknown base stat -> 0")
	eq(DataRegistry.get_species_types(99999).size(), 0, "unknown types -> empty")
	var ls := DataRegistry.get_learnset(99999)
	# four empty arrays, never an empty dict, so callers can index freely
	eq((ls["levelUp"] as Array).size(), 0, "levelUp")
	eq((ls["machine"] as Array).size(), 0, "machine")
	eq((ls["egg"] as Array).size(), 0, "egg")
	eq((ls["tutor"] as Array).size(), 0, "tutor")


func test_move_record_matches_the_contract() -> void:
	var m := DataRegistry.get_move(85)          # Thunderbolt, the contract example
	eq(String(m.get("name", "")), "Thunderbolt", "name")
	eq(String(m.get("type", "")), "electric", "type")
	eq(String(m.get("category", "")), "special", "category")
	eq(int(m.get("power", 0)), 90, "power")
	eq(int(m.get("accuracy", 0)), 100, "accuracy")
	eq(int(m.get("pp", 0)), 15, "pp")
	eq(int(m.get("priority", -99)), 0, "priority")
	eq(DataRegistry.get_move_by_name("thunderbolt"), m, "lookup by slug")
	eq(DataRegistry.get_move_by_name("Thunderbolt"), m, "lookup by display name")


func test_learnset_lookup() -> void:
	var ls := DataRegistry.get_learnset(25)
	check((ls["levelUp"] as Array).size() > 0, "Pikachu has a level-up list")
	var at_one := DataRegistry.moves_learned_at(25, 1)
	is_true(at_one.has("thunder-shock"), "Pikachu knows thunder-shock at level 1")
	is_true(Array(ls["machine"]).has("thunderbolt"), "thunderbolt is a machine move")
	eq(DataRegistry.moves_learned_at(25, 999).size(), 0, "no moves at level 999")


func test_level_caps_match_the_design_ladder() -> void:
	# docs/research/game-design.md 2.5
	eq(DataRegistry.get_level_cap(0), 14, "start")
	eq(DataRegistry.get_level_cap(1), 14, "roark")
	eq(DataRegistry.get_level_cap(2), 22, "gardenia")
	eq(DataRegistry.get_level_cap(3), 26, "fantina")
	eq(DataRegistry.get_level_cap(4), 32, "maylene")
	eq(DataRegistry.get_level_cap(8), 50, "volkner")
	eq(DataRegistry.get_level_cap(13), 62, "cynthia")
	eq(DataRegistry.get_level_cap(14), 100, "post-game")
	eq(DataRegistry.post_game_cap(), 100, "postGameCap")
	eq(DataRegistry.cap_rule(), "hard-xp-stop", "rule")
	# out of range clamps rather than crashing
	eq(DataRegistry.get_level_cap(-5), 14, "negative index clamps to the first cap")
	eq(DataRegistry.get_level_cap(999), 100, "past the end gives the post-game cap")
	eq(DataRegistry.find_cap_index_for("badge:coal"), 1, "coal clears row 1")
	eq(DataRegistry.find_cap_index_for("badge:forest"), 2, "forest clears row 2")
	eq(DataRegistry.find_cap_index_for("nonsense"), -1, "unknown event -> -1")


func test_missing_directory_degrades_gracefully() -> void:
	# The pipeline has not run: no data/, no fixtures. The registry must still
	# boot, report empty tables, and still answer level-cap questions from the
	# built-in ladder -- a null cap would break every exp calculation.
	DataRegistry.allow_fixture_fallback = false
	var ok := DataRegistry.boot("res://tests/fixtures/definitely_not_here")
	is_false(ok, "boot reports degraded")
	eq(DataRegistry.species_count(), 0, "no species")
	eq(DataRegistry.source_of("species"), "missing", "species source")
	eq(DataRegistry.source_of("level_caps"), "builtin", "caps source")
	eq(DataRegistry.level_cap_count(), 15, "built-in ladder still present")
	eq(DataRegistry.get_level_cap(2), 22, "built-in cap still correct")
	eq(DataRegistry.get_type_effectiveness("electric", "water"), 1.0,
		"no chart -> neutral, not a crash")
	DataRegistry.allow_fixture_fallback = true


func test_source_reporting() -> void:
	DataRegistry.boot(DataRegistry.FIXTURE_DIR)
	eq(DataRegistry.source_of("species"), "data",
		"booting the fixture dir directly reports it as the data dir")
	eq(DataRegistry.source_of("no_such_table"), "missing", "unknown stem")


func test_the_real_data_directory_agrees_with_the_design_ladder() -> void:
	# Cross-stream integration check: when the pipeline has produced
	# data/level_caps.json, its numbers must match the LOCKED cap ladder in
	# CLAUDE.md / docs/research/level-curve.md 1.2 -- the engine reads this
	# table on every exp award. The old 14..62 vanilla-derived ladder from
	# game-design.md 2.5 was superseded by the 18..100 rescale; the builtin
	# FALLBACK_CAPS and tests/fixtures still carry the old numbers (degraded
	# mode only), which is why the two ladder tests disagree.
	DataRegistry.boot(DataRegistry.DATA_DIR)
	if DataRegistry.source_of("level_caps") != "data":
		pending("data/level_caps.json not generated yet (source=%s)"
			% DataRegistry.source_of("level_caps"))
		return
	eq(DataRegistry.level_cap_count(), 15, "15 rows")
	var expected := [18, 18, 27, 36, 45, 54, 66, 78, 90, 96, 97, 98, 99, 100, 100]
	for i in expected.size():
		eq(DataRegistry.get_level_cap(i), expected[i], "row %d cap" % i)
	# Per-segment EXP multipliers (DATA_CONTRACT 8). test_exp_multiplier.gd owns
	# the numbers; this is the shape guard that every row has one and that the
	# permanently-null top-level field is not what answers.
	eq(DataRegistry.exp_multiplier_mode(), "per-segment", "expMultiplierMode")
	for i in expected.size():
		check(DataRegistry.get_level_cap_entry(i).has("expMultiplier"),
			"row %d carries its own expMultiplier" % i)
		check(DataRegistry.get_exp_multiplier(i) >= 1.0,
			"row %d multiplier is floored at 1.0, got %f"
			% [i, DataRegistry.get_exp_multiplier(i)])
	eq(DataRegistry.find_cap_index_for("badge:coal"), 1, "coal clears row 1")
	eq(DataRegistry.find_cap_index_for("badge:beacon"), 8, "beacon clears row 8")
	eq(DataRegistry.cap_rule(), "hard-xp-stop", "rule")
