extends Node
## Loads every `data/*.json` file described by docs/DATA_CONTRACT.md exactly once
## at boot and hands out typed accessors.
##
## THREE THINGS THIS FILE EXISTS TO GET RIGHT
##
## 1. JSON floats every number. Verified on this binary:
##    `typeof(JSON.parse_string('{"a":5}')["a"]) == 3` (TYPE_FLOAT), not 2 (TYPE_INT).
##    Species ids, move ids, levels and stats are all integers and a float used as a
##    Dictionary key or an array index is a bug that surfaces hours later. Every
##    parsed payload therefore goes through [method _intify] once, at load time, so
##    nothing downstream ever sees a float where the contract says int.
##    The type chart is the one file that is genuinely float-valued and is exempt.
##
## 2. Missing files must not be fatal. `data/` is generated by the Python pipeline
##    (`python tools/build_all.py`) and by a parallel work stream. When a file is
##    absent the registry falls back to `tests/fixtures/<same name>` and says so
##    loudly, so the engine streams can keep working against real, contract-shaped
##    data. [method source_of] reports where each table actually came from; the test
##    suite uses it to distinguish "the logic is wrong" from "the data isn't built yet".
##
## 3. Level caps always resolve. If neither data/ nor fixtures are present the
##    built-in [constant FALLBACK_CAPS] (docs/research/game-design.md 2.5) is used,
##    so [method get_level_cap] can never return a nonsense value.
##
## Nothing here is ROM-derived; species/move/ability/type data comes from veekun.

const DATA_DIR := "res://data"
const FIXTURE_DIR := "res://tests/fixtures"

const F_SPECIES := "species.json"
const F_MOVES := "moves.json"
const F_LEARNSETS := "learnsets.json"
const F_ABILITIES := "abilities.json"
const F_TYPECHART := "typechart.json"
const F_LEVEL_CAPS := "level_caps.json"

## National dex size the finished `data/species.json` must have.
const EXPECTED_SPECIES := 1025

## Used when a cap row carries no usable `expMultiplier` (the built-in fallback
## ladder, or a row written before DATA_CONTRACT 8 grew the field). 1.0 = vanilla
## rates, which is the safe direction: it under-supplies rather than over-levels.
const DEFAULT_EXP_MULTIPLIER := 1.0

## Where a table came from.
enum Source { MISSING, DATA, FIXTURE, BUILTIN }
const SOURCE_NAMES: Array = ["missing", "data", "fixture", "builtin"]

## Last-resort level cap table. Mirrors docs/research/game-design.md 2.5 and the
## `data/level_caps.json` shape in docs/DATA_CONTRACT.md 8.
const FALLBACK_CAPS: Array = [
	{"index": 0, "checkpoint": "start", "cap": 14, "raisedBy": null},
	{"index": 1, "checkpoint": "roark", "cap": 14, "raisedBy": "badge:coal"},
	{"index": 2, "checkpoint": "gardenia", "cap": 22, "raisedBy": "badge:forest"},
	{"index": 3, "checkpoint": "fantina", "cap": 26, "raisedBy": "badge:relic"},
	{"index": 4, "checkpoint": "maylene", "cap": 32, "raisedBy": "badge:cobble"},
	{"index": 5, "checkpoint": "crasher_wake", "cap": 37, "raisedBy": "badge:fen"},
	{"index": 6, "checkpoint": "byron", "cap": 41, "raisedBy": "badge:mine"},
	{"index": 7, "checkpoint": "candice", "cap": 44, "raisedBy": "badge:icicle"},
	{"index": 8, "checkpoint": "volkner", "cap": 50, "raisedBy": "badge:beacon"},
	{"index": 9, "checkpoint": "aaron", "cap": 53, "raisedBy": "flag:aaron_defeated"},
	{"index": 10, "checkpoint": "bertha", "cap": 55, "raisedBy": "flag:bertha_defeated"},
	{"index": 11, "checkpoint": "flint", "cap": 57, "raisedBy": "flag:flint_defeated"},
	{"index": 12, "checkpoint": "lucian", "cap": 59, "raisedBy": "flag:lucian_defeated"},
	{"index": 13, "checkpoint": "cynthia", "cap": 62, "raisedBy": "flag:hall_of_fame"},
	{"index": 14, "checkpoint": "postgame", "cap": 100, "raisedBy": null},
]

## Set false (before `boot()`) to make a missing `data/` file simply empty instead
## of falling back to `tests/fixtures/`. Exported builds do this automatically.
var allow_fixture_fallback: bool = true

var _species: Dictionary = {}      # int dex id -> Dictionary
var _species_order: Array = []     # dex ids, ascending
var _moves: Dictionary = {}        # int move id -> Dictionary
var _moves_by_name: Dictionary = {}# String slug -> Dictionary
var _learnsets: Dictionary = {}    # int dex id -> Dictionary
var _abilities: Dictionary = {}    # int ability id -> Dictionary
var _abilities_by_slug: Dictionary = {}# String slug -> Dictionary
var _typechart: Dictionary = {}    # String atk -> Dictionary(String def -> float)
var _caps: Array = []              # Array[Dictionary], ascending by index
var _post_game_cap: int = 100
var _cap_rule: String = "hard-xp-stop"
var _exp_multiplier_mode: String = "per-segment"

var _sources: Dictionary = {}      # String file stem -> Source
var _loaded: bool = false
var _load_msec: int = 0


func _ready() -> void:
	if OS.has_feature("template"):
		allow_fixture_fallback = false
	boot()


## Load (or reload) every table. Safe to call more than once; tests call it with
## an explicit directory. Returns true when every contract file resolved to real
## data (fixtures and built-ins do not count).
func boot(dir_path: String = DATA_DIR) -> bool:
	var t0 := Time.get_ticks_msec()
	_clear()

	_load_species(dir_path)
	_load_moves(dir_path)
	_load_learnsets(dir_path)
	_load_abilities(dir_path)
	_load_typechart(dir_path)
	_load_level_caps(dir_path)

	_loaded = true
	_load_msec = Time.get_ticks_msec() - t0

	var degraded: Array = []
	for k: String in _sources:
		if _sources[k] != Source.DATA:
			degraded.append("%s=%s" % [k, SOURCE_NAMES[_sources[k]]])
	Log.info("loaded %d species, %d moves, %d learnsets, %d abilities, %d types, %d caps in %d ms" % [
		_species.size(), _moves.size(), _learnsets.size(), _abilities.size(),
		_typechart.size(), _caps.size(), _load_msec], "DataRegistry")
	if not degraded.is_empty():
		degraded.sort()
		Log.warn("degraded tables (run `python tools/build_all.py`): %s" % ", ".join(PackedStringArray(degraded)),
			"DataRegistry")
	return degraded.is_empty()


func is_loaded() -> bool:
	return _loaded


func load_msec() -> int:
	return _load_msec


## "data" | "fixture" | "builtin" | "missing" for a file stem such as "species".
func source_of(stem: String) -> String:
	return SOURCE_NAMES[_sources.get(stem, Source.MISSING)]


# --------------------------------------------------------------------------
# Species  (DATA_CONTRACT 1)
# --------------------------------------------------------------------------

## Returns the species record, or an empty Dictionary when [param id] is unknown.
## Never returns null, so callers can use `.get(...)` without a null check.
func get_species(id: int) -> Dictionary:
	return _species.get(id, {})


func has_species(id: int) -> bool:
	return _species.has(id)


func species_count() -> int:
	return _species.size()


## Dex ids present, ascending.
func species_ids() -> PackedInt32Array:
	return PackedInt32Array(_species_order)


## `stat` is one of hp/atk/def/spa/spd/spe. Returns 0 for an unknown species.
func get_base_stat(id: int, stat: String) -> int:
	var s: Dictionary = _species.get(id, {})
	if s.is_empty():
		return 0
	var stats: Dictionary = s.get("stats", {})
	return int(stats.get(stat, 0))


## ["electric"] or ["dragon", "ground"]; empty for an unknown species.
func get_species_types(id: int) -> PackedStringArray:
	var s: Dictionary = _species.get(id, {})
	if s.is_empty():
		return PackedStringArray()
	return PackedStringArray(s.get("types", []))


# --------------------------------------------------------------------------
# Moves  (DATA_CONTRACT 2)
# --------------------------------------------------------------------------

func get_move(id: int) -> Dictionary:
	return _moves.get(id, {})


## Look a move up by its lowercase hyphenated slug, the form learnsets use
## ("thunder-shock"). Also accepts the display name ("Thunder Shock").
func get_move_by_name(move_name: String) -> Dictionary:
	return _moves_by_name.get(_slug(move_name), {})


func move_count() -> int:
	return _moves.size()


# --------------------------------------------------------------------------
# Learnsets  (DATA_CONTRACT 3)
# --------------------------------------------------------------------------

## `{"levelUp": [[1, "thunder-shock"], ...], "machine": [...], "egg": [...],
## "tutor": [...]}`. Every key is guaranteed present; missing species give
## four empty arrays rather than an empty Dictionary, so callers can index freely.
func get_learnset(id: int) -> Dictionary:
	return _learnsets.get(id, {"levelUp": [], "machine": [], "egg": [], "tutor": []})


## Move slugs this species learns on exactly [param level].
func moves_learned_at(id: int, level: int) -> PackedStringArray:
	var out := PackedStringArray()
	for pair: Array in get_learnset(id)["levelUp"]:
		if pair.size() >= 2 and int(pair[0]) == level:
			out.append(String(pair[1]))
	return out


func learnset_count() -> int:
	return _learnsets.size()


# --------------------------------------------------------------------------
# Abilities  (DATA_CONTRACT 4)
# --------------------------------------------------------------------------

func get_ability(id: int) -> Dictionary:
	return _abilities.get(id, {})


## Look an ability up by its lowercase hyphenated slug ("rough-skin"), the form
## `species.abilities` and the engine registry both use. Also accepts the display
## name ("Rough Skin"). Mirrors [method get_move_by_name]: everything downstream
## holds slugs, and a by-id-only accessor forces every caller to scan the table.
func get_ability_by_name(ability_name: String) -> Dictionary:
	return _abilities_by_slug.get(_slug(ability_name), {})


func ability_count() -> int:
	return _abilities.size()


# --------------------------------------------------------------------------
# Type chart  (DATA_CONTRACT 5)
# --------------------------------------------------------------------------

## Attacking type vs defending type, e.g. ("electric", "water") -> 2.0.
## Unknown type names return 1.0 (neutral) and log once at DEBUG, so a typo
## degrades to "no effect on the maths" instead of crashing a battle.
func get_type_effectiveness(atk: String, def: String) -> float:
	var row: Dictionary = _typechart.get(atk.to_lower(), {})
	if row.is_empty():
		if not _typechart.is_empty():
			Log.debug("unknown attacking type '%s'" % atk, "DataRegistry")
		return 1.0
	if not row.has(def.to_lower()):
		Log.debug("unknown defending type '%s'" % def, "DataRegistry")
		return 1.0
	return float(row[def.to_lower()])


## Effectiveness against a dual type: the product of the two lookups.
func get_type_multiplier(atk: String, defender_types: PackedStringArray) -> float:
	var mult := 1.0
	for t in defender_types:
		mult *= get_type_effectiveness(atk, t)
	return mult


func type_names() -> PackedStringArray:
	var out := PackedStringArray(_typechart.keys())
	out.sort()
	return out


# --------------------------------------------------------------------------
# Level caps  (DATA_CONTRACT 8)
# --------------------------------------------------------------------------

## Maximum level a Pokemon can reach at checkpoint [param index]. Out-of-range
## indices clamp: below 0 gives the first cap, past the end gives the post-game cap.
func get_level_cap(index: int) -> int:
	if _caps.is_empty():
		return _post_game_cap
	if index < 0:
		return int(_caps[0]["cap"])
	if index >= _caps.size():
		return _post_game_cap
	return int(_caps[index]["cap"])


## The whole row: index / checkpoint / cap / raisedBy (+ optional location, ace).
func get_level_cap_entry(index: int) -> Dictionary:
	if index < 0 or index >= _caps.size():
		return {}
	return _caps[index]


func level_cap_count() -> int:
	return _caps.size()


func post_game_cap() -> int:
	return _post_game_cap


func cap_rule() -> String:
	return _cap_rule


## "per-segment". DATA_CONTRACT 8 defines no other mode; the field exists so a
## data file written for a different one is visible rather than silently obeyed.
func exp_multiplier_mode() -> String:
	return _exp_multiplier_mode


## The EXP multiplier of cap row [param index] -- DATA_CONTRACT 8.
##
## PER-SEGMENT, NEVER GLOBAL. Caps are hard, so EXP surplus inside a segment is
## discarded rather than carried forward, and every segment must independently
## supply enough EXP to reach its own cap. One global number cannot express that:
## the early segments already run a 1.76-2.58 surplus at 1.0x while the League
## runs as low as 0.39, so a flat multiplier big enough to fix the tail caps the
## player a few trainers into the game. The top-level `expMultiplier` in
## `data/level_caps.json` is therefore permanently null and is never read.
##
## Out-of-range indices clamp to the nearest real row, matching
## [method get_level_cap]. A missing, null, non-numeric or non-positive value
## degrades to [constant DEFAULT_EXP_MULTIPLIER] rather than zeroing every EXP
## award in the game.
func get_exp_multiplier(index: int) -> float:
	if _caps.is_empty():
		return DEFAULT_EXP_MULTIPLIER
	var i := clampi(index, 0, _caps.size() - 1)
	var raw: Variant = (_caps[i] as Dictionary).get("expMultiplier")
	if typeof(raw) != TYPE_INT and typeof(raw) != TYPE_FLOAT:
		return DEFAULT_EXP_MULTIPLIER
	var m := float(raw)
	if not is_finite(m) or m <= 0.0:
		Log.error("cap row %d has expMultiplier %s; using %.1f" % [
			i, raw, DEFAULT_EXP_MULTIPLIER], "DataRegistry")
		return DEFAULT_EXP_MULTIPLIER
	return m


## Index of the cap row whose `raisedBy` equals [param event]
## ("badge:coal", "flag:hall_of_fame"), or -1. GameState uses this to advance the
## active cap: clearing the row's event moves you to the NEXT row.
func find_cap_index_for(event: String) -> int:
	for i in _caps.size():
		# `raisedBy` is null on the first and last rows, and String(null) is not a
		# legal constructor call -- it throws "Nonexistent 'String' constructor".
		var raised: Variant = (_caps[i] as Dictionary).get("raisedBy")
		if raised == null:
			continue
		if String(raised) == event:
			return i
	return -1


# --------------------------------------------------------------------------
# Loading
# --------------------------------------------------------------------------

func _clear() -> void:
	_species.clear()
	_species_order.clear()
	_moves.clear()
	_moves_by_name.clear()
	_learnsets.clear()
	_abilities.clear()
	_abilities_by_slug.clear()
	_typechart.clear()
	_caps.clear()
	_sources.clear()
	_post_game_cap = 100
	_cap_rule = "hard-xp-stop"
	_exp_multiplier_mode = "per-segment"


## Reads `<dir>/<file>`; falls back to `tests/fixtures/<file>`. Returns null when
## neither exists or the JSON is malformed. Records the winner in `_sources`.
func _read(dir_path: String, file_name: String) -> Variant:
	var stem := file_name.get_basename()
	var primary := dir_path.path_join(file_name)
	var parsed: Variant = _parse(primary)
	if parsed != null:
		_sources[stem] = Source.DATA
		return parsed

	if allow_fixture_fallback and dir_path != FIXTURE_DIR:
		var fixture := FIXTURE_DIR.path_join(file_name)
		parsed = _parse(fixture)
		if parsed != null:
			_sources[stem] = Source.FIXTURE
			Log.warn("%s missing -> using fixture %s" % [primary, fixture], "DataRegistry")
			return parsed

	_sources[stem] = Source.MISSING
	Log.warn("%s missing and no fixture available" % primary, "DataRegistry")
	return null


func _parse(path: String) -> Variant:
	if not FileAccess.file_exists(path):
		return null
	var text := FileAccess.get_file_as_string(path)
	if text.is_empty():
		Log.error("%s is empty" % path, "DataRegistry")
		return null
	var json := JSON.new()
	var err := json.parse(text)
	if err != OK:
		Log.error("%s: JSON parse error on line %d: %s" % [
			path, json.get_error_line(), json.get_error_message()], "DataRegistry")
		return null
	return json.data


func _load_species(dir_path: String) -> void:
	var raw: Variant = _read(dir_path, F_SPECIES)
	if raw == null:
		return
	var rows: Array = []
	if raw is Array:
		rows = raw
	elif raw is Dictionary:
		# tolerate an id-keyed object as well as the contract's array
		for k: Variant in (raw as Dictionary):
			rows.append((raw as Dictionary)[k])
	else:
		Log.error("species.json must be an array", "DataRegistry")
		return
	for r: Variant in rows:
		if not (r is Dictionary):
			continue
		var d: Dictionary = _intify(r) as Dictionary
		var id := int(d.get("id", 0))
		if id <= 0:
			Log.warn("species row without a usable id skipped", "DataRegistry")
			continue
		_species[id] = d
		_species_order.append(id)
	_species_order.sort()


func _load_moves(dir_path: String) -> void:
	var raw: Variant = _read(dir_path, F_MOVES)
	if raw == null:
		return
	var rows: Array = []
	if raw is Array:
		rows = raw
	elif raw is Dictionary:
		for k: Variant in (raw as Dictionary):
			rows.append((raw as Dictionary)[k])
	for r: Variant in rows:
		if not (r is Dictionary):
			continue
		var d: Dictionary = _intify(r) as Dictionary
		var id := int(d.get("id", 0))
		if id <= 0:
			continue
		_moves[id] = d
		_moves_by_name[_slug(String(d.get("name", "")))] = d


func _load_learnsets(dir_path: String) -> void:
	var raw: Variant = _read(dir_path, F_LEARNSETS)
	if raw == null:
		return
	if not (raw is Dictionary):
		Log.error("learnsets.json must be an object keyed by dex id", "DataRegistry")
		return
	for key: Variant in (raw as Dictionary):
		var id := int(String(key))
		var entry: Variant = (raw as Dictionary)[key]
		if not (entry is Dictionary):
			continue
		var d: Dictionary = (entry as Dictionary).duplicate()
		# Learnsets are ~850 KB and almost entirely move-name strings; running the
		# whole payload through _intify() cost ~700 ms of boot rebuilding string
		# arrays that have no numbers in them. The only numbers here are the
		# levelUp levels, so convert exactly those.
		var lv: Array = []
		for pair: Variant in (d.get("levelUp", []) as Array):
			if pair is Array and (pair as Array).size() >= 2:
				lv.append([int((pair as Array)[0]), String((pair as Array)[1])])
		d["levelUp"] = lv
		for k in ["machine", "egg", "tutor"]:
			if not d.has(k):
				d[k] = []
		_learnsets[id] = d


func _load_abilities(dir_path: String) -> void:
	var raw: Variant = _read(dir_path, F_ABILITIES)
	if raw == null:
		return
	var rows: Array = []
	if raw is Array:
		rows = raw
	elif raw is Dictionary:
		for k: Variant in (raw as Dictionary):
			rows.append((raw as Dictionary)[k])
	for r: Variant in rows:
		if not (r is Dictionary):
			continue
		var d: Dictionary = _intify(r) as Dictionary
		_abilities[int(d.get("id", 0))] = d
		var slug := _slug(String(d.get("slug", d.get("name", ""))))
		if not slug.is_empty():
			_abilities_by_slug[slug] = d


func _load_typechart(dir_path: String) -> void:
	var raw: Variant = _read(dir_path, F_TYPECHART)
	if raw == null:
		return
	if not (raw is Dictionary):
		Log.error("typechart.json must be an object", "DataRegistry")
		return
	var src: Dictionary = raw
	# tolerate a wrapper object: {"chart": {...}}
	if src.has("chart") and src["chart"] is Dictionary:
		src = src["chart"]
	for atk: Variant in src:
		var row: Variant = src[atk]
		if not (row is Dictionary):
			continue
		var out: Dictionary = {}
		for def: Variant in (row as Dictionary):
			# deliberately NOT _intify'd: 0.5 and 2.0 are real floats here
			out[String(def).to_lower()] = float((row as Dictionary)[def])
		_typechart[String(atk).to_lower()] = out


func _load_level_caps(dir_path: String) -> void:
	var raw: Variant = _read(dir_path, F_LEVEL_CAPS)
	if raw == null or not (raw is Dictionary):
		_caps = FALLBACK_CAPS.duplicate(true)
		_sources["level_caps"] = Source.BUILTIN
		Log.warn("level caps fell back to the built-in table (%d rows)" % _caps.size(),
			"DataRegistry")
		return
	var d: Dictionary = _intify(raw) as Dictionary
	var caps: Array = d.get("caps", [])
	if caps.is_empty():
		_caps = FALLBACK_CAPS.duplicate(true)
		_sources["level_caps"] = Source.BUILTIN
		Log.warn("level_caps.json has no rows; using the built-in table", "DataRegistry")
		return
	caps.sort_custom(func(a: Dictionary, b: Dictionary) -> bool:
		return int(a.get("index", 0)) < int(b.get("index", 0)))
	_caps = caps
	_post_game_cap = int(d.get("postGameCap", 100))
	_cap_rule = String(d.get("rule", "hard-xp-stop"))
	_exp_multiplier_mode = String(d.get("expMultiplierMode", "per-segment"))
	# DATA_CONTRACT 8: the top-level expMultiplier is permanently null. Nothing
	# may read it as a value -- an earlier build ran a flat 2.5 from here and it
	# capped the player four trainers in. Shout if it ever comes back.
	if d.get("expMultiplier") != null:
		Log.error("level_caps.json has a top-level expMultiplier (%s); it must be "
			% d.get("expMultiplier")
			+ "null -- EXP multipliers are per-segment (DATA_CONTRACT 8). Ignoring it.",
			"DataRegistry")
	if _exp_multiplier_mode != "per-segment":
		Log.error("level_caps.json expMultiplierMode is '%s'; this engine only "
			% _exp_multiplier_mode
			+ "implements 'per-segment' (DATA_CONTRACT 8)", "DataRegistry")


# --------------------------------------------------------------------------
# Helpers
# --------------------------------------------------------------------------

## Recursively turn JSON's floats back into ints wherever the value is integral.
## Applied to every table except the type chart. This is the single boundary where
## the TYPE_FLOAT contamination described in the header is fixed.
func _intify(v: Variant) -> Variant:
	match typeof(v):
		TYPE_FLOAT:
			var f: float = v
			if is_finite(f) and absf(f) < 9.007199254740992e15 and f == floor(f):
				return int(f)
			return f
		TYPE_DICTIONARY:
			var out: Dictionary = {}
			for k: Variant in (v as Dictionary):
				out[k] = _intify((v as Dictionary)[k])
			return out
		TYPE_ARRAY:
			var arr: Array = []
			for e: Variant in (v as Array):
				arr.append(_intify(e))
			return arr
	return v


func _slug(s: String) -> String:
	return s.to_lower().replace(" ", "-").replace("_", "-")
