#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Make every impossible evolution possible in data/species.json.

Single-player game: no trading, no link cable, no clock, no Alola/Galar
locations, no Legends: Arceus move styles.  73 evolution edges in the veekun
dump cannot be performed.  This script rewrites them under the owner's four
rules (docs/research/evolution-audit.md section 9):

    1. trade                  -> level up at a chosen level
    2. trade + held item      -> level up while holding that item
    3. item-gated impossible  -> level up while holding that item
    4. anything else wacky    -> level up (or, where a plain level would break
                                a sibling branch, an explicit use-item route)

and deletes the 11 edges that are impossible *and* redundant, because a
blanket level-up there would destroy a working branch (Eevee is the extreme
case: two bare level-up edges would eat all eight other Eeveelutions).

    python tools/fix_evolutions.py              # dry run, prints the diff
    python tools/fix_evolutions.py --apply      # rewrite data/species.json
    python tools/fix_evolutions.py --markdown   # emit the design table
    python tools/fix_evolutions.py --verify     # audit only, no table

Idempotent: re-running after --apply reports "already applied" and writes
nothing.  data/species.json is regenerated by tools/build_species.py, which
reads the raw veekun CSVs and knows nothing about this pass -- so this script
must be re-run after every build_species.py run.

Shape note: the replacements use the vocabulary data/species.json already
speaks -- method "level-up" plus "level" / "heldItem" (see DATA_CONTRACT 1).
"level up while holding said item" is exactly {"method":"level-up",
"heldItem":<item>}, which 20 edges in the file already use (Gligar, Happiny),
so no new method string and no contract change is needed.
"""

from __future__ import print_function

import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SPECIES = os.path.join(ROOT, 'data', 'species.json')

# --------------------------------------------------------------------------
# Level policy, stated once and applied throughout.
#
# L37  every plain trade evolution.  One above the Fantina cap (36), so the
#      line unlocks the instant the Relic Badge lifts the cap to 45.  It is
#      also the value the owner's own "no impossible evos" ROM patch uses,
#      verified by a NARC diff (game-design.md 5.5), and it keeps Machamp,
#      Golem, Gengar and Trevenant out of the windows game-design.md 5.2
#      bans them from.
# L40  single-stage "regional upgrade" evolutions whose base never evolved
#      before (Sirfetch'd, Wyrdeer, Overqwil, Basculegion, Melmetal).
# --   item-gated routes get NO level: the item is the gate, which keeps them
#      cap-neutral.  This is also what the ROM patch does.
# keep where the only impossible part was a *condition* (timeOfDay,
#      upsideDown, needsRain, full-moon, in-battle), the canon level or
#      happiness value survives untouched.
# else pre-evolution level + ~8-14, then checked against the cap in force
#      where the line is actually found.
# --------------------------------------------------------------------------

TRADE_LEVEL = 37
UPGRADE_LEVEL = 40

# fromDex, toDex, old method, expected old condition keys, action, new edge, rationale
TABLE = [
    # ---- rule 1: plain trade -> level up at L37 (ROM-patch value) ---------
    (64, 65, 'trade', {}, 'convert', {'method': 'level-up', 'level': TRADE_LEVEL},
     'ROM-patch value. Abra is on Route 203 pre-badge-2; L37 keeps Alakazam out of gyms 1-3.'),
    (67, 68, 'trade', {}, 'convert', {'method': 'level-up', 'level': TRADE_LEVEL},
     'ROM-patch value. Machop wild L17; Machamp is Fighting, banned before Roark (5.2).'),
    (75, 76, 'trade', {}, 'convert', {'method': 'level-up', 'level': TRADE_LEVEL},
     'ROM-patch value. Golem is Rock/Ground, banned before Roark (5.2).'),
    (93, 94, 'trade', {}, 'convert', {'method': 'level-up', 'level': TRADE_LEVEL},
     'ROM-patch value. Gengar lands the moment Fantina is beaten and Gengarite is awarded.'),
    (525, 526, 'trade', {}, 'convert', {'method': 'level-up', 'level': TRADE_LEVEL},
     'Same rule, Gen 5. Roggenrola is Oreburgh Gate L5-7, Boldore L25, so 12 levels of carry.'),
    (533, 534, 'trade', {}, 'convert', {'method': 'level-up', 'level': TRADE_LEVEL},
     'Same rule, Gen 5. Timburr->Gurdurr is L25.'),
    (708, 709, 'trade', {}, 'convert', {'method': 'level-up', 'level': TRADE_LEVEL},
     'Phantump is Eterna Forest L16 night-only; L37 puts Trevenant after the Ghost gym (4.3).'),
    (710, 711, 'trade', {}, 'convert', {'method': 'level-up', 'level': TRADE_LEVEL},
     'Same rule, Gen 6.'),
    # ---- rule 1 variant: trade for a species -> plain level --------------
    (588, 589, 'trade', {'tradeSpecies': 616}, 'convert',
     {'method': 'level-up', 'level': TRADE_LEVEL},
     'Karrablast<->Shelmet mutual trade dropped; owner asked for a flat level on both halves.'),
    (616, 617, 'trade', {'tradeSpecies': 588}, 'convert',
     {'method': 'level-up', 'level': TRADE_LEVEL},
     'Other half of the same swap.'),

    # ---- rule 2: trade holding an item -> level up holding that item -----
    (61, 186, 'trade', {'heldItem': 'kings-rock'}, 'convert',
     {'method': 'level-up', 'heldItem': 'kings-rock'},
     'Cap-neutral: the item is the gate. Poliwhirl keeps Water Stone -> Poliwrath.'),
    (79, 199, 'trade', {'heldItem': 'kings-rock'}, 'convert',
     {'method': 'level-up', 'heldItem': 'kings-rock'},
     'Owner rule 2 kept literally. Needs the specificity precedence rule against L37 -> Slowbro; '
     'Slowking is double-covered by the surviving use-item galarica-wreath edge either way.'),
    (95, 208, 'trade', {'heldItem': 'metal-coat'}, 'convert',
     {'method': 'level-up', 'heldItem': 'metal-coat'}, 'ROM-patch pairing.'),
    (112, 464, 'trade', {'heldItem': 'protector'}, 'convert',
     {'method': 'level-up', 'heldItem': 'protector'}, 'ROM-patch pairing.'),
    (117, 230, 'trade', {'heldItem': 'dragon-scale'}, 'convert',
     {'method': 'level-up', 'heldItem': 'dragon-scale'}, 'ROM-patch pairing.'),
    (123, 212, 'trade', {'heldItem': 'metal-coat'}, 'convert',
     {'method': 'level-up', 'heldItem': 'metal-coat'},
     "Scyther keeps Black Augurite -> Kleavor; the branches differ by item, so no collision."),
    (125, 466, 'trade', {'heldItem': 'electirizer'}, 'convert',
     {'method': 'level-up', 'heldItem': 'electirizer'}, 'ROM-patch pairing.'),
    (126, 467, 'trade', {'heldItem': 'magmarizer'}, 'convert',
     {'method': 'level-up', 'heldItem': 'magmarizer'}, 'ROM-patch pairing.'),
    (137, 233, 'trade', {'heldItem': 'up-grade'}, 'convert',
     {'method': 'level-up', 'heldItem': 'up-grade'}, 'ROM-patch pairing.'),
    (233, 474, 'trade', {'heldItem': 'dubious-disc'}, 'convert',
     {'method': 'level-up', 'heldItem': 'dubious-disc'}, 'ROM-patch pairing.'),
    (349, 350, 'trade', {'heldItem': 'prism-scale'}, 'convert',
     {'method': 'level-up', 'heldItem': 'prism-scale'},
     'Becomes the ONLY Milotic route once the Beauty edge is deleted.'),
    (356, 477, 'trade', {'heldItem': 'reaper-cloth'}, 'convert',
     {'method': 'level-up', 'heldItem': 'reaper-cloth'}, 'ROM-patch pairing.'),
    (366, 367, 'trade', {'heldItem': 'deep-sea-tooth'}, 'convert',
     {'method': 'level-up', 'heldItem': 'deep-sea-tooth'},
     'The two Clamperl branches stay separated by which item it holds.'),
    (366, 368, 'trade', {'heldItem': 'deep-sea-scale'}, 'convert',
     {'method': 'level-up', 'heldItem': 'deep-sea-scale'}, 'Other Clamperl branch.'),
    (682, 683, 'trade', {'heldItem': 'sachet'}, 'convert',
     {'method': 'level-up', 'heldItem': 'sachet'}, 'Same rule, Gen 6.'),
    (684, 685, 'trade', {'heldItem': 'whipped-dream'}, 'convert',
     {'method': 'level-up', 'heldItem': 'whipped-dream'}, 'Same rule, Gen 6.'),

    # ---- rule 4: drop the dead condition, keep everything else -----------
    (19, 20, 'level-up', {'level': 20, 'timeOfDay': 'night'}, 'convert',
     {'method': 'level-up', 'level': 20}, 'timeOfDay dropped; L20 is the vanilla Kanto route.'),
    (104, 105, 'level-up', {'level': 28, 'timeOfDay': 'night'}, 'convert',
     {'method': 'level-up', 'level': 28}, 'timeOfDay dropped; L28 is canon.'),
    (207, 472, 'level-up', {'heldItem': 'razor-fang', 'timeOfDay': 'night'}, 'convert',
     {'method': 'level-up', 'heldItem': 'razor-fang'},
     'timeOfDay dropped; the Razor Fang alone is the gate. Cap-neutral.'),
    (215, 461, 'level-up', {'heldItem': 'razor-claw', 'timeOfDay': 'night'}, 'convert',
     {'method': 'level-up', 'heldItem': 'razor-claw'},
     'Weavile keeps the vanilla-canon Razor Claw route; Sneasel is a Platinum native.'),
    (264, 862, 'level-up', {'level': 35, 'timeOfDay': 'night'}, 'convert',
     {'method': 'level-up', 'level': 35}, 'timeOfDay dropped; L35 is canon.'),
    (406, 315, 'level-up', {'happiness': 160, 'timeOfDay': 'day'}, 'convert',
     {'method': 'level-up', 'happiness': 160}, 'timeOfDay dropped; friendship survives.'),
    (433, 358, 'level-up', {'happiness': 220, 'timeOfDay': 'night'}, 'convert',
     {'method': 'level-up', 'happiness': 220}, 'timeOfDay dropped; friendship survives.'),
    (440, 113, 'level-up', {'heldItem': 'oval-stone', 'timeOfDay': 'day'}, 'convert',
     {'method': 'level-up', 'heldItem': 'oval-stone'}, 'timeOfDay dropped; Oval Stone is the gate.'),
    (447, 448, 'level-up', {'happiness': 160, 'timeOfDay': 'day'}, 'convert',
     {'method': 'level-up', 'happiness': 160},
     'timeOfDay dropped; Riolu is an in-game gift, friendship survives.'),
    (686, 687, 'level-up', {'level': 30, 'upsideDown': True}, 'convert',
     {'method': 'level-up', 'level': 30}, 'upsideDown dropped; L30 is canon and inside Fantina 36.'),
    (696, 697, 'level-up', {'level': 39, 'timeOfDay': 'day'}, 'convert',
     {'method': 'level-up', 'level': 39}, 'timeOfDay dropped; L39 is canon.'),
    (698, 699, 'level-up', {'level': 39, 'timeOfDay': 'night'}, 'convert',
     {'method': 'level-up', 'level': 39}, 'timeOfDay dropped; L39 is canon.'),
    (705, 706, 'level-up', {'level': 50, 'needsRain': True}, 'convert',
     {'method': 'level-up', 'level': 50}, 'needsRain dropped; L50 is canon, inside the Wake segment.'),
    (734, 735, 'level-up', {'level': 20, 'timeOfDay': 'day'}, 'convert',
     {'method': 'level-up', 'level': 20}, 'timeOfDay dropped; L20 is canon.'),
    (744, 745, 'level-up', {'level': 25, 'timeOfDay': 'day'}, 'convert',
     {'method': 'level-up', 'level': 25},
     'timeOfDay dropped. Only Midday Lycanroc exists in the data, so nothing is lost.'),
    (753, 754, 'level-up', {'level': 34, 'timeOfDay': 'day'}, 'convert',
     {'method': 'level-up', 'level': 34}, 'timeOfDay dropped; L34 is canon.'),
    (872, 873, 'level-up', {'happiness': 160, 'timeOfDay': 'night'}, 'convert',
     {'method': 'level-up', 'happiness': 160}, 'timeOfDay dropped; friendship survives.'),
    (971, 972, 'level-up', {'level': 30, 'timeOfDay': 'night'}, 'convert',
     {'method': 'level-up', 'level': 30}, 'timeOfDay dropped; L30 is canon.'),
    (217, 901, 'use-item', {'item': 'peat-block', 'timeOfDay': 'full-moon'}, 'convert',
     {'method': 'use-item', 'item': 'peat-block'},
     'Only the lunar phase was impossible. Peat Block is an ordinary placeable item.'),

    # ---- rule 4: wacky trigger -> plain level up ------------------------
    (57, 979, 'use-move', {}, 'convert', {'method': 'level-up', 'level': 35},
     'Rage Fist x20 dropped. Mankey->Primeape is L28; 35 sits inside the Fantina cap.'),
    (83, 865, 'three-critical-hits', {}, 'convert',
     {'method': 'level-up', 'level': UPGRADE_LEVEL},
     'Crit counter dropped. Single-stage upgrade band.'),
    (211, 904, 'level-up', {'knownMove': 'barb-barrage'}, 'convert',
     {'method': 'level-up', 'level': UPGRADE_LEVEL},
     'knownMove dropped: Qwilfish learns Barb Barrage as an egg move only and the sole other '
     'learner is Overqwil itself, so the route was circular (audit 3.7).'),
    (234, 899, 'agile-style-move', {}, 'convert',
     {'method': 'level-up', 'level': UPGRADE_LEVEL},
     'Agile style dropped. Single-stage upgrade band.'),
    (550, 902, 'recoil-damage', {'gender': 2}, 'convert',
     {'method': 'level-up', 'level': UPGRADE_LEVEL, 'gender': 2},
     '294-recoil counter dropped; gender 2 KEPT (already an engine-supported condition).'),
    (625, 983, 'three-defeated-bisharp', {}, 'convert',
     {'method': 'level-up', 'level': 60},
     "Leader's Crest hunt dropped. Pawniard->Bisharp is L52, so Kingambit must clear 52; "
     '60 needs the Byron cap (66).'),
    (808, 809, 'meltan-candies', {}, 'convert',
     {'method': 'level-up', 'level': UPGRADE_LEVEL},
     '400 candies dropped. Meltan has no wild slot, so placement is still required.'),
    (868, 869, 'spin', {}, 'convert', {'method': 'level-up', 'level': 30},
     'Stick-spin + Sweet dropped. Milcery is a Gen 8 base stage; 30 is inside Fantina 36.'),
    (922, 923, 'level-up', {}, 'convert', {'method': 'level-up', 'level': 32},
     'Walk-1000-steps trigger absent from the dump, leaving a bare level-up. '
     'Pawmi is Route 202 L4, Pawmo L18; 32 is inside Fantina 36.'),
    (924, 925, 'in-battle-level-up', {'level': 25}, 'convert',
     {'method': 'level-up', 'level': 25},
     'One-token fix: the L25 already in the data is kept, only the trigger changes.'),
    (946, 947, 'level-up', {}, 'convert', {'method': 'level-up', 'level': 30},
     'Bare level-up (walk-1000-steps absent). Base stage, so the 30 band.'),
    (953, 954, 'level-up', {}, 'convert', {'method': 'level-up', 'level': 30},
     'Bare level-up (walk-1000-steps absent). Base stage, so the 30 band.'),
    (999, 1000, 'gimmighoul-coins', {}, 'convert', {'method': 'level-up', 'level': 45},
     '999 coins dropped. 45 == the Maylene cap, which a Pokemon still REACHES; the cap only '
     'stops further gain.'),

    # ---- rule 4, branch-safe: needs a discriminator, not a bare level ----
    (133, 196, 'level-up', {'happiness': 160, 'timeOfDay': 'day'}, 'convert',
     {'method': 'use-item', 'item': 'sun-stone'},
     'Day/night was the ONLY thing separating Espeon from Umbreon. Sun Stone is unused on '
     'Eevee, thematically exact, needs no clock, and keeps the branch player-chosen.'),
    (133, 197, 'level-up', {'happiness': 160, 'timeOfDay': 'night'}, 'convert',
     {'method': 'use-item', 'item': 'moon-stone'}, 'Mirror of the Espeon fix.'),
    (215, 903, 'level-up', {'heldItem': 'razor-claw', 'timeOfDay': 'day'}, 'convert',
     {'method': 'level-up', 'heldItem': 'razor-fang'},
     'Weavile and Sneasler shared one item and were split only by day/night. Razor Fang pairs '
     'naturally with Razor Claw, is already in the data (Gliscor), and makes both branches '
     'opt-in -- a bare L45 would be inert, since wild Sneasel is L58+ in the rescaled tables.'),
    (562, 867, 'take-damage', {'location': 'dusty-bowl'}, 'convert',
     {'method': 'use-item', 'item': 'dusk-stone'},
     'Yamask already has L34 -> Cofagrigus, so NO plain level works: below 34 every Yamask '
     'becomes Runerigus, above it none survives. use-item is a different trigger, so the '
     'branch is collision-free (the Charcadet/Applin pattern). Dusk Stone is the ghost stone '
     'and is already in the data.'),

    # ---- delete: impossible AND redundant -------------------------------
    (82, 462, 'level-up', {'location': 'blush-mountain'}, 'delete', None,
     "Alola's Blush Mountain. Magneton already has use-item thunder-stone -- Magnezone is safe."),
    (299, 476, 'level-up', {'location': 'blush-mountain'}, 'delete', None,
     'Nosepass already has use-item thunder-stone -- Probopass is safe.'),
    (133, 470, 'level-up', {'location': 'lush-jungle'}, 'delete', None,
     'CRITICAL: converting this to a bare level-up would make every Eevee become Leafeon on '
     'its next level-up and destroy all eight other Eeveelutions. use-item leaf-stone covers it.'),
    (133, 471, 'level-up', {'location': 'mount-lanakila'}, 'delete', None,
     'Same critical reason as Leafeon. use-item ice-stone already covers Glaceon.'),
    (737, 738, 'level-up', {'location': 'vast-poni-canyon'}, 'delete', None,
     'Charjabug already has use-item thunder-stone.'),
    (739, 740, 'level-up', {'location': 'mount-lanakila'}, 'delete', None,
     'Crabrawler already has use-item ice-stone.'),
    (349, 350, 'level-up', {'beauty': 170}, 'delete', None,
     'No Poffin/contest Beauty stat. The Prism Scale route replaces it.'),
    (211, 904, 'strong-style-move', {}, 'delete', None,
     'Duplicate third edge to Overqwil; the converted edge above covers it.'),
    (211, 904, 'use-move', {}, 'delete', None, 'Duplicate second edge to Overqwil.'),
    (891, 892, 'tower-of-darkness', {}, 'delete', None,
     'Duplicate of Kubfu use-item scroll-of-darkness, which is performable.'),
    (891, 892, 'tower-of-waters', {}, 'delete', None,
     'No scroll-of-waters edge exists anywhere in the data and there is no form system, so '
     'Rapid Strike Urshifu is form-absent regardless. Kubfu also has no wild slot.'),
]

# Methods and condition keys that cannot be performed in this game.  Used by
# the verifier, which must report zero of them after --apply.
DEAD_METHODS = set([
    'trade', 'use-move', 'three-critical-hits', 'strong-style-move',
    'agile-style-move', 'recoil-damage', 'take-damage',
    'three-defeated-bisharp', 'meltan-candies', 'spin', 'tower-of-darkness',
    'tower-of-waters', 'in-battle-level-up', 'gimmighoul-coins',
])
DEAD_KEYS = set(['timeOfDay', 'location', 'beauty', 'upsideDown', 'needsRain',
                 'tradeSpecies'])
# knownMove edges whose move no species can teach the pre-evolution.
DEAD_KNOWN_MOVES = set(['barb-barrage'])


def load():
    with open(SPECIES, encoding='utf-8') as fh:
        return json.load(fh)


def save(data):
    with open(SPECIES, 'w', encoding='utf-8') as fh:
        json.dump(data, fh, separators=(',', ':'), sort_keys=True)
        fh.write('\n')


def find(edges, to, method):
    hits = [i for i, e in enumerate(edges)
            if e.get('to') == to and e.get('method') == method]
    return hits


def audit(data):
    """Return the list of still-impossible edges."""
    bad = []
    for sp in data:
        for e in sp.get('evolutions', []):
            why = None
            if e.get('method') in DEAD_METHODS:
                why = 'method=' + str(e.get('method'))
            else:
                dead = sorted(DEAD_KEYS.intersection(e.keys()))
                if dead:
                    why = 'condition=' + ','.join(dead)
                elif e.get('knownMove') in DEAD_KNOWN_MOVES:
                    why = 'unlearnable knownMove=' + str(e.get('knownMove'))
                elif (e.get('method') == 'level-up'
                      and len(set(e.keys()) - set(['to', 'method'])) == 0):
                    why = 'bare level-up: no level, no condition'
            if why:
                bad.append((sp['id'], sp['name'], e.get('to'), why))
    return bad


def apply_table(data, verbose=True):
    by_id = dict((sp['id'], sp) for sp in data)
    changed = skipped = 0
    errors = []
    # Deletions last, and by descending index, so earlier indices stay valid.
    for frm, to, method, old, action, new, _why in TABLE:
        sp = by_id.get(frm)
        if sp is None:
            errors.append('dex %d missing from species.json' % frm)
            continue
        edges = sp.setdefault('evolutions', [])
        hits = find(edges, to, method)
        if not hits:
            # Idempotence: is the target state already in place?
            if action == 'delete':
                skipped += 1
                continue
            want = dict(new)
            want['to'] = to
            if any(e == want for e in edges):
                skipped += 1
                continue
            errors.append('%s #%d -> %d: no %s edge and no converted edge either'
                          % (sp['name'], frm, to, method))
            continue
        if len(hits) > 1:
            errors.append('%s #%d -> %d: %d edges share method %s'
                          % (sp['name'], frm, to, len(hits), method))
            continue
        i = hits[0]
        edge = edges[i]
        expect = dict(old)
        expect['to'] = to
        expect['method'] = method
        if edge != expect:
            errors.append('%s #%d -> %d: edge is %s, design expected %s'
                          % (sp['name'], frm, to, json.dumps(edge, sort_keys=True),
                             json.dumps(expect, sort_keys=True)))
            continue
        if action == 'delete':
            edges.pop(i)
            if verbose:
                print('  DELETE  %-14s #%-4d -> %-4d  %s' % (sp['name'], frm, to, method))
        else:
            want = dict(new)
            want['to'] = to
            edges[i] = want
            if verbose:
                print('  REWRITE %-14s #%-4d -> %-4d  %s  ==>  %s'
                      % (sp['name'], frm, to, method, json.dumps(want, sort_keys=True)))
        changed += 1
    return changed, skipped, errors


def markdown():
    rows = ['| from | to | old method | old condition | new method | new condition | why |',
            '|---|---|---|---|---|---|---|']
    data = load()
    name = dict((sp['id'], sp['name']) for sp in data)
    for frm, to, method, old, action, new, why in TABLE:
        oldc = ', '.join('`%s=%s`' % (k, old[k]) for k in sorted(old)) or '--'
        if action == 'delete':
            nm, nc = '**DELETE**', '--'
        else:
            nm = '`%s`' % new['method']
            nc = ', '.join('`%s=%s`' % (k, new[k]) for k in sorted(new) if k != 'method') or '--'
        rows.append('| %s (%d) | %s (%d) | `%s` | %s | %s | %s | %s |'
                    % (name.get(frm, '?'), frm, name.get(to, '?'), to, method, oldc, nm, nc, why))
    return '\n'.join(rows)


def main(argv):
    if '--markdown' in argv:
        print(markdown())
        return 0

    data = load()
    before = audit(data)
    print('impossible edges before: %d' % len(before))

    if '--verify' in argv:
        for row in before:
            print('  #%-4d %-14s -> %-4d  %s' % row)
        return 0 if not before else 1

    print('design table: %d edges (%d rewrite, %d delete)'
          % (len(TABLE),
             len([r for r in TABLE if r[4] == 'convert']),
             len([r for r in TABLE if r[4] == 'delete'])))
    changed, skipped, errors = apply_table(data)
    print('applied %d, already-applied %d, errors %d' % (changed, skipped, len(errors)))
    for e in errors:
        print('  ERROR ' + e)
    if errors:
        print('REFUSING to write: the data does not match the design table.')
        return 1

    after = audit(data)
    print('impossible edges after: %d' % len(after))
    for row in after:
        print('  STILL IMPOSSIBLE #%-4d %-14s -> %-4d  %s' % row)

    if '--apply' not in argv:
        print('dry run: data/species.json untouched (pass --apply to write)')
        return 0 if not after else 1

    if changed == 0:
        print('nothing to write: already applied')
        return 0 if not after else 1

    save(data)
    # Assert on content, not on exit code: re-read from disk and re-audit.
    check = audit(load())
    print('re-read from disk: %d impossible edges' % len(check))
    if check:
        print('FAILED: impossible edges survived the write')
        return 1
    print('wrote %s' % SPECIES)
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
